/** Sync with backend `src/constants/storeCategories.js` — ids used for i18n `dash.store.categories.<id>`. */
export const STORE_CATEGORY_IDS = [
  "cement",
  "steel_rebar",
  "bricks_blocks",
  "sand_fine",
  "crush_aggregate",
  "gravel",
  "roofing_sheets_tiles",
  "pvc_pipes_fittings",
  "electrical_wires_cables",
  "switches_breakers",
  "lighting_fixtures",
  "interior_paint",
  "exterior_paint",
  "primer_putty",
  "wood_timber",
  "plywood_mdf",
  "tiles_ceramic",
  "marble_granite",
  "glass_aluminium",
  "nails_screws_fasteners",
  "hand_tools",
  "power_tools",
  "safety_equipment",
  "waterproofing",
  "insulation",
  "doors_windows",
  "sanitary_fittings",
  "kitchen_bath",
  "adhesives_sealants",
  "chemicals_solvents",
  "ladders_scaffolding",
  "generators_pumps",
  "plastic_pipes_hdpe",
  "wire_mesh_binding",
  "water_tanks",
  "agri_lawn",
  "other",
];

export const STORE_UNITS = ["piece", "bag", "kg", "ton", "sqft", "litre", "pack", "drum", "bundle"];
